M48
; DRILL file {KiCad (6.0.6-0)} date 2022 December 31, Saturday 16:02:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-31T16:02:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X118.745Y-62.23
X118.745Y-95.25
X171.45Y-62.23
X171.45Y-95.25
T0
M30
